task 2_1
VLiamin/spbu pull request #40
Opened 2019-02-28 16:48 UTC by VLiamin

2019-03-08 20:14 UTC, PrikhodkoStanislav requested changes

2019-03-08 20:14 UTC, PrikhodkoStanislav commented on sem2/hw2/task2_1/SortArray.java
> +/**
однострочные комментарии лучше так и писать в одну строку: /** ... */

2019-03-08 20:14 UTC, PrikhodkoStanislav commented on sem2/hw2/task2_1/Insert.java
> +        System.out.println("\nInsert sorting");
Вывод сообщений на консоль не очень хорошо вставлять в реализацию алгоритма. Лучше вынести в метод main.

2019-03-08 20:14 UTC, PrikhodkoStanislav commented on sem2/hw2/task2_1/Insert.java
> +        int[] copyOfArray = arrayOfNumbers.clone();
Почему создается копия списка? Можно сразу работать с переданным списком.

2019-03-08 20:14 UTC, PrikhodkoStanislav commented on sem2/hw2/task2_1/Bubble.java
> +    public static void main(String[] args) {
Метод main лучше выносить из класса реализации алгоритма в отдельный класс. Алгоритм должен работать в разрыве от его частного использования.

2019-03-08 20:14 UTC, PrikhodkoStanislav commented on sem2/hw2/task2_1/Bubble.java
> +        System.out.print("\nBubble sort");
Опять же лишний вывод текста и копия массива.

2019-03-11 09:53 UTC, jzuken commented
и можно уже, наконец, писать адекватные комментарии к коммитам? в следующий раз заставлю переделывать всю историю

2019-03-28 20:13 UTC, PrikhodkoStanislav requested changes

2019-03-28 20:13 UTC, PrikhodkoStanislav commented on sem2/hw2/task2_1/Bubble.java
> +        System.out.println();
Это здесь лишнее.

2019-03-28 20:13 UTC, PrikhodkoStanislav commented on sem2/hw2/task2_1/Insert.java
> +        for (i = 1; i < arrayOfNumbers.length; i++){
Пробелы перед открывающими фигурными скобками!

2019-04-29 07:45 UTC, jzuken requested changes

2019-04-29 07:45 UTC, jzuken commented on sem2/hw2/task2_1/Bubble.java
> +    private int i = 0;
а с какой целью они поля класса? уровня видимости внутри метода вполне достаточно

2019-04-29 07:45 UTC, jzuken commented on sem2/hw2/task2_1/Bubble.java
> +public class Bubble implements SortArray {
Bubble -- это пузырь, а ты пишешь сортировщик. не надо сокращать в именах, пиши полностью

2019-04-29 07:45 UTC, jzuken commented on sem2/hw2/task2_1/Bubble.java
> +    public void run(int[] arrayOfNumbers) {
метод тоже лучше назвать как-то типа sort(), run слишком обобщённо

2019-05-11 13:47 UTC, jzuken requested changes

2019-05-11 13:47 UTC, jzuken commented on sem2/hw2/task2_1/BubbleSort.java
> +    private static int temp = 0;
всё ещё непонятно, почему это поле, ещё и статическое

2019-05-11 13:47 UTC, jzuken commented on sem2/hw2/task2_1/BubbleSort.java
> +package ru.liamin.vladimir;
посмотри, пожалуйста, какую файловую структуру от тебя ждёт gradle: https://docs.gradle.org/current/userguide/organizing_gradle_projects.html. без неё всё это бессмысленно, оно же не работает

2019-05-11 16:46 UTC, closed without merging