added task4_2
VLiamin/spbu pull request #47
Opened 2019-03-31 20:37 UTC by VLiamin

2019-05-04 16:51 UTC, jzuken commented on sem2/hw4/task4_2/ru/liamin/vladimir/AVLTree.java
> +    private class NodeElement {
а зачем тут такое разделение?

2019-05-17 13:30 UTC, jzuken requested changes

2019-05-17 13:30 UTC, jzuken commented on sem2/hw4/task4_2/ru/liamin/vladimir/AVLTree.java
> +        head = new NodeElement();
лучше совместить с объявлением поля

2019-05-17 13:30 UTC, jzuken commented on sem2/hw4/task4_2/ru/liamin/vladimir/AVLTree.java
> +        if (head.root == null)
позор такое писать к концу первого курса

2019-05-17 13:30 UTC, jzuken commented on sem2/hw4/task4_2/ru/liamin/vladimir/AVLTree.java
> +        private void printToArray(ArrayList elements) {
:(

2019-05-17 14:43 UTC, VLiamin commented on sem2/hw4/task4_2/ru/liamin/vladimir/AVLTree.java
> +        if (head.root == null)
Извините

2019-06-08 09:37 UTC, jzuken requested changes

2019-06-08 09:37 UTC, jzuken commented on sem2/hw4/task4_2/src/main/java/ru/liamin/vladimir/AVLTree.java
> +            return true;
да я не про root тут писал, а про эти return'ы

2019-06-11 10:58 UTC, merged