added task 3.1
VLiamin/spbu pull request #6
Opened 2018-11-03 16:14 UTC by VLiamin

2018-11-03 16:46 UTC, ujohnny commented
второй коммит зааменддить к первому

2018-11-07 11:22 UTC, jzuken requested changes

2018-11-07 11:22 UTC, jzuken commented on sem1/hw3/task3_1.cpp
> +	bool isRepeat = false;
`repeats` или `isRepeated`

2018-11-24 17:07 UTC, jzuken commented
ну нет, тут этого всгео не нужно с мерджами. сейчас надо откатиться к коммиту 94f007d, сделать ему amend, поправить комментарий на более адекватный и выложить новый коммит сюда

2018-12-12 09:21 UTC, merged